### PR TITLE
Add micro-api-client pagination

### PR DESCRIPTION
**Pull request by bcomnes**
**- Summary**

This still requires the pagination parameters to be added to open-api. 

**- Test plan**

We should have a test server and make sure we get the right shape back.

**- Description for the changelog**

Adds pagination data to paginated responses.

```js
data.pagination = { next: 2, last: 2, current: 1, total: null }
```

### CODE REVIEW

**Comment by bcomnes** [comment]
WIP till I there are some tests on this.  Also, this is going to be a really bad breaking change.

**Comment by bcomnes** [comment]
Maybe we can do this without a breaking change, adding pagination as an array property?

**Comment by bcomnes** [comment]
Ok, I modified this to not be a breaking change.  What do you think @DavidWells ?

Also, the total value is blank because bitbaloon does not return `X-Total-Count`.  Maybe we should have the pagination calculate this?

**Comment by sw-yx** [comment]
seems unobjectionable. but i have v little contextual knowledge to be of use here.

**Comment by bcomnes** [comment]
I spoke with @DavidWells last week over DM.  Sounds like we should have a chat this week about this. He suggested we aim for the ideal API shape.  I agree, though I worry we'll never get around to it due to the pain / refactoring involved.  If we take an iterative approach, (e.g. the array property), we could at least gain the benefit of this without jumping that hurdle now.  But it would also increase the probability of never refactoring to get to the ideal shape.

**Comment by sw-yx** [comment]
we never got around to this :(

**Comment by bcomnes** [comment]
FWIW, this is a working solution.

**Comment by JGAntunes** [comment]
Addressed via #283, further discussion in #285. Thanks for the work you've put into this 🙌

**Pull request closed without merging**
