### PR TITLE
uses open library instead of openBrowser function

### PR DESCRIPTION
**Pull request by tzmanics**
**- Summary**

For the authorization example in the `README.md`, switches out the use of the `openBrowser` function to the [open library](https://github.com/sindresorhus/open) as suggested by @ehmicky. This makes the example a little more encapsulated.

**- A picture of a cute animal (not mandatory but encouraged)**
main-qimg-0ed1eb8b029f487633cce500ceac79fa

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Comment by tzmanics** [comment]
Hi @erezrokah thanks for the 👍, on further review, I saw another fix in changing `api` to `client` to match the other example code in the readme. Sorry for the change, hope it's ok!

**Review by erezrokah — APPROVED** [review]

**Comment by erezrokah** [comment]
> Hi @erezrokah thanks for the 👍, on further review, I saw another fix in changing `api` to `client` to match the other example code in the readme. Sorry for the change, hope it's ok!

This is great, thank you for following up with that fix :)

**Comment by erezrokah** [comment]
@tzmanics I changed the required checks per https://github.com/netlify/js-client/pull/271
Let me know when you're ready and I can merge this one (or you can wait for https://github.com/netlify/js-client/pull/271 and rebase).

**Comment by tzmanics** [comment]
I think it's good to merge this one now and I can re-check after #271 is merged. THanks!

**Pull request merged**
