### PR TITLE
add umd build

### PR DESCRIPTION
**Pull request by leonardodino**
**- Summary**

add `umd` build via webpack v4 + babel v7

**- Test plan**

**- Description for the changelog**

publish `umd` build

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by bcomnes** [comment]
Thank you @leonardodino.  What is your use case?  Are you looking to use this with unpkg or similar workflow?

**Comment by bcomnes** [comment]
I'm open to it, and was actually planning on doing something similar once I had time to implement some baseline browser testing.

**Comment by bcomnes** [comment]
I'm releasing the CLI tomorrow, and will check this out sometime after.  Thank you for the contribution!

**Comment by leonardodino** [comment]
nice! (:

**Comment by bcomnes** [comment]
🎉`netlify@2.1.0`🎉

**Pull request merged**
