### PR TITLE
feat!: remove deploy method

### LINKED ISSUE #157: Feature: consider moving js-client deploy logic to the CLI
At the moment most of the CLI deploy command logic in handled by the `js-client`:
https://github.com/netlify/js-client/blob/9d3945c1bb3f8d96b734f3eca1d90c717fa38558/src/deploy/index.js#L42

This seems out of place for a client that should be wrapping our open-api spec.
Also, it prevents this client from being browser compatible.

It might makes sense to move that logic to the CLI, since we're already implementing some deploy logic in the CLI as a part of edge handlers:
https://github.com/netlify/cli/pull/1244

### PR DESCRIPTION
**Pull request by eduardoboucas**
**- Summary**

Removes the `deploy` method, as it was added to the CLI.

Closes #157.

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
🧹

**Comment by eduardoboucas** [comment]
@erezrokah I've updated the README in https://github.com/netlify/js-client/pull/437/commits/a3cfa1daca7f22b82892bb2415afb0f3aca461cf. Could you give it a final 👀  and ✅ , please?

**Comment by erezrokah** [comment]
> @erezrokah I've updated the README in [a3cfa1d](https://github.com/netlify/js-client/commit/a3cfa1daca7f22b82892bb2415afb0f3aca461cf). Could you give it a final 👀 and ✅ , please?

Arg, I always forget the readme changes. Nice catch!

**Review by erezrokah — APPROVED** [review]

**Comment by CEbbinghaus** [comment]
I know this is done and dusted but I'm wondering why? 
It seems to me that there isn't a reason it could exist in both packages.

Now instead of being able to directly call the function through js and pass the parameters as the arguments to a function, I have to build a string command and run it via `child_process.exec`.

is there any security risk and if not it is not advised to use <7.0.0 versions since that would be my next step.

**Comment by erezrokah** [comment]
Hi @CEbbinghaus, you can see the reasoning in the related issue https://github.com/netlify/js-client/issues/157.

> is there any security risk and if not it is not advised to use <7.0.0 versions since that would be my next step.

We don't update dependencies nor back-port new features to older versions. So if there's a vulnerable dependency it will still be a part of the older version.

**Pull request merged**
